### ISSUE TITLE
Addon loaded, but not working

### ISSUE THREAD

**Issue by prplneon** [jofner/Questomatic#7]
Addon shows as enabled and loaded, but does not show up in the interface options or by using any of the /qm shortcuts.  This issue started on 9/5/16.  I have deleted and re-installed the addon multiple times and disabled all other addons with no effect.

**Comment by jofner** [comment]
Try delete SavedVariables for this addon in \WTF\Account\{AccountName}\SavedVariables\Questomatic.lua

**Comment by jofner** [comment]
I point you to this FAQ about addons
http://us.battle.net/forums/en/wow/topic/1536706542

**Comment by prplneon** [comment]
Neither of those helped, but I figured out how to fix it.  Deleted the addon entirely again, installed 2.3.1 which worked.  Reinstalled 2.5 and it is still functioning.
